### ISSUE TITLE
Ensure that AToMPM setup works with Python 3.10

### ISSUE THREAD

**Issue by BentleyJOakes** [AToMPM/atompm#151]
There may be an issue with using AToMPM with Python3.10:

"
Probably a problem on my end, issue with python 3.10, kept getting error message ModuleNotFoundError: No module named '_distutils_hack'. Turns out it is from the module symbol that comes with setuptools, which was declared deprecated in Python3.9 and removed altogether in Python 3.10. Can be fixed using pip3 install setuptools or by downgrading Python.
    Kept getting seg faults with Python 3.10 despite installing setuptools, so created a new conda environment with Python 3.9 instead which fixed it.
"

**Comment by vasco-sousa** [comment]
Can we discuss this further? I might need more info, as I have not been able to replicate this.

**Comment by BentleyJOakes** [comment]
I'll close this for now as the CI is running on Python 3.10 already and it should catch any installation issues.
